amount = int(input("Enter the amount:"))
i = 0
while(i<=amount):
    if(amount >= 500):
        count = amount // 500
        print(f'500 ::{count}' ,end= ' ')
        amount = amount % 500
    elif(amount >= 200):
        count = amount // 200
        print(f'200 ::{count}' ,end= ' ')
        amount = amount % 200
    elif(amount >= 100):
        count = amount // 100
        print(f'100 ::{count}' ,end= ' ')
        amount = amount % 100
    elif(amount >= 50):
        count = amount // 50
        print(f'50 ::{count}' ,end= ' ')
        amount = amount % 50
    elif(amount >= 20):
        count = amount // 20
        print(f'20 ::{count}' ,end= ' ')
        amount = amount % 20
    elif(amount >= 10):
        count = amount // 10
        print(f'10 ::{count}' ,end= ' ')
        count = amount % 10
    i += 1
    